spring.application.name=es
server.port=8081

#elastic-search config
spring.data.elasticsearch.cluster-name=dev-cluster
spring.data.elasticsearch.cluster-node=localhost:9200

spring.datasource.url=jdbc:postgresql://localhost:5432/flowable-db?currentSchema=public
spring.datasource.username=flowable-db-user
spring.datasource.password=flowable-db@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.maximum-pool-size=10

flowable.database-schema-update=true
flowable.async-executor-activate=false
flowable.check-process-definitions=true

